# Pandas DataFrame 完全指南

DataFrame 是 Pandas 中最核心的数据结构，它是一个二维标记表格数据结构，类似于 Excel 表格或 SQL 表。本教程将系统讲解 DataFrame 的各种操作技巧。

## 1. DataFrame 的创建方式

DataFrame 可以从多种数据源创建，常见的方式包括：从字典创建、从 Series 创建、从 CSV 文件读取等。下面我们分别演示这些创建方法。

In [1]:
import pandas as pd
import numpy as np

# 方法一：通过 Series 创建 DataFrame
s1 = pd.Series([1, 2, 3, 4, 5])
s2 = pd.Series([6, 7, 8, 9, 10])
df_from_series = pd.DataFrame({"第1列": s1, "第2列": s2})
print("通过 Series 创建的 DataFrame：")
df_from_series

通过 Series 创建的 DataFrame：

   第1列  第2列
0    1    6
1    2    7
2    3    8
3    4    9
4    5   10

In [2]:
# 方法二：通过字典创建 DataFrame（最常用的方式）
df = pd.DataFrame(
    {
        "name": ["tom", "jack", "alice", "bob", "allen"],
        "age": [15, 17, 20, 26, 30],
        "score": [60.5, 80, 30.6, 70, 83.5]
    },
    index=[1, 2, 3, 4, 5],
    columns=["name", "score", "age"]  # 可以指定列的顺序
)
df

    name  score  age
1    tom   60.5   15
2   jack   80.0   17
3  alice   30.6   20
4    bob   70.0   26
5  allen   83.5   30

## 2. DataFrame 的基本属性

DataFrame 提供了多个属性来查看数据的结构信息，包括行索引、列标签、数据类型、形状等。

In [3]:
print("行索引（Index）：")
print(df.index)
print("\n列标签（Columns）：")
print(df.columns)
print("\n数据值（values）：")
print(df.values)

行索引（Index）：
Index([1, 2, 3, 4, 5], dtype='int64')

列标签（Columns）：
Index(['name', 'score', 'age'], dtype='str')

数据值（values）：
[['tom' 60.5 15]
 ['jack' 80.0 17]
 ['alice' 30.6 20]
 ['bob' 70.0 26]
 ['allen' 83.5 30]]

In [4]:
print("维度数：", df.ndim)
print("形状（行数, 列数）：", df.shape)
print("元素总个数：", df.size)
print("\n各列数据类型：")
print(df.dtypes)

维度数： 2
形状（行数, 列数）： (5, 3)
元素总个数： 15

各列数据类型：
name         str
score    float64
age        int64
dtype: object

In [5]:
# 行列转置（Transpose）
print("转置后的 DataFrame：")
df.T

转置后的 DataFrame：

          1     2      3     4      5
name    tom  jack  alice   bob  allen
score  60.5  80.0   30.6  70.0   83.5
age      15    17     20    26     30

## 3. DataFrame 数据访问

Pandas 提供了多种数据访问方式，适用于不同的场景：
- `loc`：基于标签访问，支持布尔数组
- `iloc`：基于整数位置访问
- `at`：快速访问单个元素（标签）
- `iat`：快速访问单个元素（整数位置）

In [6]:
# 获取某一行（使用 loc 和 iloc）
print("使用 loc 获取索引为 4 的行：")
print(df.loc[4])
print("\n使用 iloc 获取第 3 行（索引为 3）：")
print(df.iloc[3])

使用 loc 获取索引为 4 的行：
name      bob
score    70.0
age        26
Name: 4, dtype: object

使用 iloc 获取第 3 行（索引为 3）：
name      bob
score    70.0
age        26
Name: 4, dtype: object

In [7]:
# 获取某一列
print("使用 loc 获取 'name' 列：")
print(df.loc[:, 'name'])
print("\n使用 iloc 获取第 0 列：")
print(df.iloc[:, 0])

使用 loc 获取 'name' 列：
1      tom
2     jack
3    alice
4      bob
5    allen
Name: name, dtype: str

使用 iloc 获取第 0 列：
1      tom
2     jack
3    alice
4      bob
5    allen
Name: name, dtype: str

In [8]:
# 快速访问单个元素
print("使用 at（标签访问）：", df.at[3, 'score'])
print("使用 iat（位置访问）：", df.iat[2, 1])
print("使用 loc：", df.loc[3, 'score'])
print("使用 iloc：", df.iloc[2, 1])

使用 at（标签访问）： 30.6
使用 iat（位置访问）： 30.6
使用 loc： 30.6
使用 iloc： 30.6

In [9]:
# 获取单列数据的不同方式
print("通过列名获取（返回 Series）：")
print(type(df['name']))
print(df['name'])
print("\n通过属性方式获取（返回 Series）：")
print(type(df.name))
print(df.name)
print("\n通过双括号获取（返回 DataFrame）：")
print(type(df[['name']]))
df[['name']]

通过列名获取（返回 Series）：
<class 'pandas.Series'>
1      tom
2     jack
3    alice
4      bob
5    allen
Name: name, dtype: str

通过属性方式获取（返回 Series）：
<class 'pandas.Series'>
1      tom
2     jack
3    alice
4      bob
5    allen
Name: name, dtype: str

通过双括号获取（返回 DataFrame）：
<class 'pandas.DataFrame'>

    name
1    tom
2   jack
3  alice
4    bob
5  allen

In [10]:
# 获取多列（传入列名列表）
df[['name', 'score']]

    name  score
1    tom   60.5
2   jack   80.0
3  alice   30.6
4    bob   70.0
5  allen   83.5

In [11]:
# 查看前 n 行数据（默认 5 行）
df.head(2)

   name  score  age
1   tom   60.5   15
2  jack   80.0   17

In [12]:
# 查看后 n 行数据（默认 5 行）
df.tail(3)

    name  score  age
3  alice   30.6   20
4    bob   70.0   26
5  allen   83.5   30

In [13]:
# 随机抽样
df.sample(3)

    name  score  age
3  alice   30.6   20
1    tom   60.5   15
5  allen   83.5   30

## 4. 布尔索引与数据筛选

布尔索引是数据筛选的核心技术，通过条件表达式生成布尔数组，然后根据布尔值筛选数据。

In [14]:
# 重新创建 DataFrame 以确保数据一致
df = pd.DataFrame(
    {
        "name": ["tom", "jack", "alice", "bob", "allen"],
        "age": [15, 17, 20, 26, 30],
        "score": [60.5, 80, 30.6, 70, 83.5]
    },
    index=[1, 2, 3, 4, 5],
    columns=["name", "score", "age"]
)

# 单条件筛选：分数大于 70 分的学生
df[df.score > 70]

    name  score  age
2   jack   80.0   17
5  allen   83.5   30

In [15]:
# 多条件筛选：分数大于 70 分且年龄小于 20 岁
df[(df['score'] > 70) & (df.age < 20)]

   name  score  age
2  jack   80.0   17

In [16]:
# 使用 isin 检查元素是否包含在指定集合中
df.isin(['jack', 20])

    name  score    age
1  False  False  False
2   True  False  False
3  False  False   True
4  False  False  False
5  False  False  False

## 5. 缺失值处理

真实数据中经常存在缺失值，Pandas 提供了多种处理缺失值的方法：
- `isna()` / `isnull()`：检测缺失值
- `dropna()`：删除包含缺失值的行或列
- `fillna()`：用指定值填充缺失值

In [17]:
# 创建包含缺失值的 DataFrame
df_with_na = pd.DataFrame(
    {
        "name": ["tom", "jack", None, "bob", "allen"],
        "age": [15, 17, 20, None, 30],
        "score": [60.5, None, 30.6, 70, 83.5]
    },
    index=[1, 2, 3, 4, 5]
)
df_with_na

    name   age  score
1    tom  15.0   60.5
2   jack  17.0    NaN
3    NaN  20.0   30.6
4    bob   NaN   70.0
5  allen  30.0   83.5

In [18]:
# 检测缺失值
df_with_na.isna()

    name    age  score
1  False  False  False
2  False  False   True
3   True  False  False
4  False   True  False
5  False  False  False

In [19]:
# 删除包含缺失值的行
df_with_na.dropna()

    name   age  score
1    tom  15.0   60.5
5  allen  30.0   83.5

In [20]:
# 用指定值填充缺失值
df_with_na.fillna(0)

    name   age  score
1    tom  15.0   60.5
2   jack  17.0    0.0
3      0  20.0   30.6
4    bob   0.0   70.0
5  allen  30.0   83.5

In [21]:
# 用列均值填充该列的缺失值
df_with_na['score'].fillna(df_with_na['score'].mean())

1    60.50
2    61.15
3    30.60
4    70.00
5    83.50
Name: score, dtype: float64

## 6. 重复值处理

数据中可能存在重复记录，需要进行处理。Pandas 提供了以下方法：
- `duplicated()`：检测重复行
- `drop_duplicates()`：删除重复行

In [22]:
# 创建包含重复行的 DataFrame
df_dup = pd.DataFrame(
    {
        "name": ["tom", "tom", "jack", "alice", "bob", "allen"],
        "age": [15, 15, 15, 20, 26, 30],
        "score": [60.5, 60.5, 80, 30.6, 70, 83.5]
    },
    index=[1, 2, 3, 4, 5, 6],
    columns=["name", "score", "age"]
)
df_dup

    name  score  age
1    tom   60.5   15
2    tom   60.5   15
3   jack   80.0   15
4  alice   30.6   20
5    bob   70.0   26
6  allen   83.5   30

In [23]:
# 检测重复行（返回布尔 Series）
print("检测所有列的重复情况：")
print(df_dup.duplicated())
print("\n仅检测 'age' 列的重复情况：")
print(df_dup.duplicated(subset=['age']))

检测所有列的重复情况：
1    False
2     True
3    False
4    False
5    False
6    False
dtype: bool

仅检测 'age' 列的重复情况：
1    False
2     True
3     True
4    False
5    False
6    False
dtype: bool

In [24]:
# 删除重复行（保留第一行）
df_dup.drop_duplicates()

    name  score  age
1    tom   60.5   15
3   jack   80.0   15
4  alice   30.6   20
5    bob   70.0   26
6  allen   83.5   30

In [25]:
# 删除重复行（保留最后一行）
df_dup.drop_duplicates(keep='last')

    name  score  age
2    tom   60.5   15
3   jack   80.0   15
4  alice   30.6   20
5    bob   70.0   26
6  allen   83.5   30

## 7. 数值替换

使用 `replace()` 方法可以将指定值替换为新值。

In [26]:
# 将所有 15 替换为 30
df_dup.replace(15, 30)

    name  score  age
1    tom   60.5   30
2    tom   60.5   30
3   jack   80.0   30
4  alice   30.6   20
5    bob   70.0   26
6  allen   83.5   30

## 8. 统计方法

DataFrame 提供了丰富的统计方法，可以快速获取数据的分布特征。

### 8.1 基础统计量

In [27]:
df = pd.DataFrame(
    {
        "name": ["tom", "tom", "jack", "alice", "bob", "allen"],
        "age": [15, 15, 15, 20, 26, 30],
        "score": [60.5, 60.5, 80, 30.6, 70, 83.5]
    },
    index=[1, 2, 3, 4, 5, 6],
    columns=["name", "score", "age"]
)

print("分数列的总和：", df['score'].sum())
print("分数列的最大值：", df.score.max())
print("年龄列的最小值：", df.age.min())
print("分数列的平均值：", df.score.mean())
print("分数列的中位数：", df.score.median())
print("年龄列的众数：", df.age.mode()[0])

分数列的总和： 385.1
分数列的最大值： 83.5
年龄列的最小值： 15
分数列的平均值： 64.18333333333334
分数列的中位数： 65.25
年龄列的众数： 15

In [28]:
# 其他统计量
print("分数列的标准差：", df.score.std())
print("分数列的方差：", df.score.var())
print("分数列的 25% 分位数：", df.score.quantile(0.25))
print("分数列的 50% 分位数：", df.score.quantile(0.5))
print("分数列的 75% 分位数：", df.score.quantile(0.75))

分数列的标准差： 19.037375519400424
分数列的方差： 362.4216666666666
分数列的 25% 分位数： 60.5
分数列的 50% 分位数： 65.25
分数列的 75% 分位数： 77.5

In [29]:
# 一次性获取所有描述性统计
df.describe()

           score        age
count   6.000000   6.000000
mean   64.183333  20.166667
std    19.037376   6.493587
min    30.600000  15.000000
25%    60.500000  15.000000
50%    65.250000  17.500000
75%    77.500000  24.500000
max    83.500000  30.000000

In [30]:
# 统计每列非缺失值的个数
df.count()

name     6
score    6
age      6
dtype: int64

In [31]:
# 统计每行每组合计出现的次数
df.value_counts()

name   score  age
tom    60.5   15     2
jack   80.0   15     1
alice  30.6   20     1
bob    70.0   26     1
allen  83.5   30     1
Name: count, dtype: int64

### 8.2 累积计算

累积计算用于查看数据随时间或顺序的累积变化。

In [32]:
# 累积求和
print("累积求和：")
df['score'].cumsum()

累积求和：

1     60.5
2    121.0
3    201.0
4    231.6
5    301.6
6    385.1
Name: score, dtype: float64

In [33]:
# 累积最小值
print("累积最小值：")
df['score'].cummin()

累积最小值：

1    60.5
2    60.5
3    60.5
4    30.6
5    30.6
6    30.6
Name: score, dtype: float64

In [34]:
# 累积最大值
print("累积最大值：")
df['score'].cummax()

累积最大值：

1    60.5
2    60.5
3    80.0
4    80.0
5    80.0
6    83.5
Name: score, dtype: float64

## 9. 数据排序

Pandas 提供了多种排序方式：
- `sort_index()`：按索引排序
- `sort_values()`：按值排序
- `nlargest()` / `nsmallest()`：获取最大/最小的 n 个元素

In [35]:
# 按索引排序（降序）
df.sort_index(ascending=False)

    name  score  age
6  allen   83.5   30
5    bob   70.0   26
4  alice   30.6   20
3   jack   80.0   15
2    tom   60.5   15
1    tom   60.5   15

In [36]:
# 按单列值排序
df.sort_values(by='score')

    name  score  age
4  alice   30.6   20
1    tom   60.5   15
2    tom   60.5   15
5    bob   70.0   26
3   jack   80.0   15
6  allen   83.5   30

In [37]:
# 按多列值排序（先按 score 升序，再按 age 降序）
df_sort = pd.DataFrame(
    {
        "name": ["tom", "tom", "jack", "alice", "bob", "allen"],
        "age": [15, 15, 15, 20, 26, 30],
        "score": [60.5, 60.5, 80, 30.6, 70, 80]
    },
    index=[1, 2, 3, 4, 5, 6],
    columns=["name", "score", "age"]
)
df_sort.sort_values(by=['score', 'age'], ascending=[True, False])

    name  score  age
4  alice   30.6   20
1    tom   60.5   15
2    tom   60.5   15
5    bob   70.0   26
6  allen   80.0   30
3   jack   80.0   15

In [38]:
# 获取分数最高的 2 条记录
df_sort.nlargest(2, ['score', 'age'])

    name  score  age
6  allen   80.0   30
3   jack   80.0   15

In [39]:
# 获取分数最低的 2 条记录
df_sort.nsmallest(2, ['score', 'age'])

    name  score  age
4  alice   30.6   20
1    tom   60.5   15

## 10. 数据类型转换

处理数据时经常需要进行类型转换。

In [40]:
# 显式转换数据类型
df['age'].astype(float)

1    15.0
2    15.0
3    15.0
4    20.0
5    26.0
6    30.0
Name: age, dtype: float64

## 11. 数据变形

数据变形是数据分析中的重要操作，包括宽表转长表、长表转宽表、以及字符串分割等。

### 11.1 宽表转长表（melt）

使用 `melt()` 函数将宽表格式转换为长表格式。

In [41]:
data = {
    'ID': [1, 2],
    'name': ['张三', '李四'],
    'Math': [90, 85],
    'English': [88, 92],
    'Science': [95, 89]
}
df_wide = pd.DataFrame(data)
print("原始宽表：")
df_wide

原始宽表：

   ID name  Math  English  Science
0   1   张三    90       88       95
1   2   李四    85       92       89

In [42]:
# 使用 melt 转为长表
df_long = pd.melt(
    df_wide,
    id_vars=['ID', 'name'],  # 保留的标识列
    var_name='科目',          # 科目列的名称
    value_name='分数'         # 分数列的名称
)
print("\n转换后的长表：")
df_long.sort_values(by=['name', '科目'])

转换后的长表：

   ID name       科目  分数
2   1   张三  English  88
0   1   张三     Math  90
4   1   张三  Science  95
3   2   李四  English  92
1   2   李四     Math  85
5   2   李四  Science  89

### 11.2 长表转宽表（pivot）

使用 `pivot()` 函数将长表格式转换为宽表格式。

In [43]:
# 将长表转回宽表
df_pivot = pd.pivot(
    df_long,
    index=['ID', 'name'],
    columns=['科目'],
    values='分数'
)
print("转换后的宽表：")
df_pivot.reset_index()

转换后的宽表：

科目  ID name  English  Math  Science
0    1   张三       88    90       95
1    2   李四       92    85       89

### 11.3 字符串分割

使用 `str.split()` 可以将字符串列拆分为多列。

In [44]:
data = {
    'ID': [1, 2],
    'name': ['alice smith', 'bob jack'],
    'Math': [90, 85],
    'English': [88, 92],
    'Science': [95, 89]
}
df_split = pd.DataFrame(data)

# 将 name 列按空格分割为名和姓两列
df_split[['first_name', 'last_name']] = df_split['name'].str.split(' ', expand=True)
df_split

   ID         name  Math  English  Science first_name last_name
0   1  alice smith    90       88       95      alice     smith
1   2     bob jack    85       92       89        bob      jack

## 12. 分组聚合

分组聚合是数据分析中最常用的操作之一，通过 `groupby()` 可以按一个或多个列进行分组，然后对每个组应用聚合函数。

常用的聚合函数包括：
- `count()`：计数
- `sum()`：求和
- `mean()`：平均值
- `max()`：最大值
- `min()`：最小值
- `agg()`：自定义聚合

In [45]:
# 创建示例数据
df_group = pd.DataFrame({
    '部门': ['销售部', '销售部', '技术部', '技术部', '人事部'],
    '姓名': ['张三', '李四', '王五', '赵六', '钱七'],
    '薪资': [8000, 9000, 12000, 11000, 7000],
    '年龄': [25, 30, 28, 32, 26]
})
df_group

    部门  姓名     薪资  年龄
0  销售部  张三   8000  25
1  销售部  李四   9000  30
2  技术部  王五  12000  28
3  技术部  赵六  11000  32
4  人事部  钱七   7000  26

In [46]:
# 按部门分组，计算薪资总和
df_group.groupby('部门')['薪资'].sum()

部门
人事部     7000
技术部    23000
销售部    17000
Name: 薪资, dtype: int64

In [47]:
# 按部门分组，计算多个统计量
df_group.groupby('部门').agg({
    '薪资': ['sum', 'mean', 'max', 'min'],
    '年龄': ['mean', 'max']
})

        薪资                           年龄
       sum     mean    max    min  mean max
部门
人事部   7000   7000.0   7000   7000  26.0  26
技术部  23000  11500.0  12000  11000  30.0  32
销售部  17000   8500.0   9000   8000  27.5  30

In [48]:
# 使用 agg 自定义聚合名称
df_group.groupby('部门')['薪资'].agg(
    薪资总和='sum',
    薪资平均='mean',
    最高薪资='max'
)

      薪资总和     薪资平均   最高薪资
部门
人事部   7000   7000.0   7000
技术部  23000  11500.0  12000
销售部  17000   8500.0   9000

## 13. 案例实战

下面通过三个综合案例，展示 DataFrame 在实际数据分析中的应用。

### 案例 1：学生成绩分析

In [49]:
# 案例 1：学生成绩分析

# 场景：某班级的学生成绩数据如下，请完成以下任务：
# 1. 计算每位学生的总分和平均分
# 2. 找出数学成绩高于 90 分或英语成绩高于 85 分的学生
# 3. 按总分从高到低排序，并输出前 3 名学生

data = {
    '姓名': ['张三', '李四', '王五', '赵六', '钱七'],
    '数学': [85, 92, 78, 88, 95],
    '英语': [90, 88, 85, 92, 80],
    '物理': [75, 80, 88, 85, 90]
}
scores = pd.DataFrame(data)

# 1. 计算每位学生的总分和平均分
scores['总分'] = scores[['数学', '英语', '物理']].sum(axis=1)
scores['平均分'] = scores[['数学', '英语', '物理']].mean(axis=1)
print("添加总分和平均分后的成绩表：")
scores

添加总分和平均分后的成绩表：

   姓名  数学  英语  物理   总分        平均分
0  张三  85  90  75  250  83.333333
1  李四  92  88  80  260  86.666667
2  王五  78  85  88  251  83.666667
3  赵六  88  92  85  265  88.333333
4  钱七  95  80  90  265  88.333333

In [50]:
# 2. 找出数学成绩高于 90 分或英语成绩高于 85 分的学生
print("数学成绩 > 90 或 英语成绩 > 85 的学生：")
scores[(scores['数学'] > 90) | (scores['英语'] > 85)]

数学成绩 > 90 或 英语成绩 > 85 的学生：

   姓名  数学  英语  物理   总分        平均分
0  张三  85  90  75  250  83.333333
1  李四  92  88  80  260  86.666667
3  赵六  88  92  85  265  88.333333
4  钱七  95  80  90  265  88.333333

In [51]:
# 3. 按总分从高到低排序，并输出前 3 名学生
print("总分排名前 3 的学生（使用 sort_values）：")
r1 = scores.sort_values('总分', ascending=False).head(3)
print(r1)

print("\n总分排名前 3 的学生（使用 nlargest）：")
r2 = scores.nlargest(3, '总分')
print(r2)

总分排名前 3 的学生（使用 sort_values）：
   姓名  数学  英语  物理   总分        平均分
4  钱七  95  80  90  265  88.333333
3  赵六  88  92  85  265  88.333333
1  李四  92  88  80  260  86.666667

总分排名前 3 的学生（使用 nlargest）：
   姓名  数学  英语  物理   总分        平均分
3  赵六  88  92  85  265  88.333333
4  钱七  95  80  90  265  88.333333
1  李四  92  88  80  260  86.666667

### 案例 2：销售数据分析

In [52]:
# 案例 2：销售数据分析

# 场景：某公司销售数据如下，请完成以下任务：
# 1. 计算每种产品的总销售额（销售额 = 单价 × 销量）
# 2. 找出销售额最高的产品
# 3. 按销售额从高到低排序，并输出所有产品信息

data = {
    '产品名称': ['A', 'B', 'C', 'D'],
    '单价': [100, 150, 200, 120],
    '销量': [50, 30, 20, 40]
}
df_sales = pd.DataFrame(data)

# 1. 计算每种产品的总销售额
df_sales['总销售额'] = df_sales['单价'] * df_sales['销量']
print("添加总销售额后的销售表：")
df_sales

添加总销售额后的销售表：

  产品名称   单价  销量  总销售额
0    A  100  50  5000
1    B  150  30  4500
2    C  200  20  4000
3    D  120  40  4800

In [53]:
# 2. 找出销售额最高的产品
print("销售额最高的产品：")
df_sales.nlargest(1, '总销售额')

销售额最高的产品：

  产品名称   单价  销量  总销售额
0    A  100  50  5000

In [54]:
# 3. 按销售额从高到低排序
print("按销售额排序（从高到低）：")
df_sales.sort_values('总销售额', ascending=False)

按销售额排序（从高到低）：

  产品名称   单价  销量  总销售额
0    A  100  50  5000
3    D  120  40  4800
1    B  150  30  4500
2    C  200  20  4000

### 案例 3：电商用户行为分析

In [55]:
# 案例 3：电商用户行为分析

# 场景：某电商平台的用户行为数据如下，请完成以下任务：
# 1. 计算每位用户的总消费金额（消费金额 = 商品单价 × 购买数量）
# 2. 找出消费金额最高的用户，并输出其所有信息
# 3. 计算所有用户的平均消费金额（保留 2 位小数）
# 4. 统计电子产品的总购买数量

data = {
    '用户ID': [101, 102, 103, 104, 105],
    '用户名': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    '商品类别': ['电子产品', '服饰', '电子产品', '家居', '服饰'],
    '商品单价': [1200, 300, 800, 150, 200],
    '购买数量': [1, 3, 2, 5, 4]
}
df_user = pd.DataFrame(data)

# 1. 计算每位用户的总消费金额
df_user['总消费金额'] = df_user['商品单价'] * df_user['购买数量']
print("添加总消费金额后的数据：")
df_user

添加总消费金额后的数据：

   用户ID      用户名  商品类别  商品单价  购买数量  总消费金额
0   101    Alice  电子产品  1200     1   1200
1   102      Bob    服饰   300     3    900
2   103  Charlie  电子产品   800     2   1600
3   104    David    家居   150     5    750
4   105      Eve    服饰   200     4    800

In [56]:
# 2. 找出消费金额最高的用户
print("消费金额最高的用户：")
df_user.nlargest(1, '总消费金额')

消费金额最高的用户：

   用户ID      用户名  商品类别  商品单价  购买数量  总消费金额
2   103  Charlie  电子产品   800     2   1600

In [57]:
# 3. 计算所有用户的平均消费金额（保留 2 位小数）
avg_amount = df_user['总消费金额'].mean()
print(f"所有用户的平均消费金额：{avg_amount:.2f}")

所有用户的平均消费金额：1050.00

In [58]:
# 4. 统计电子产品的总购买数量
electronics_qty = df_user[df_user['商品类别'] == '电子产品']['购买数量'].sum()
print(f"电子产品的总购买数量：{electronics_qty}")

电子产品的总购买数量：3

## 14. 字符串处理

Pandas 提供了强大的字符串处理能力，通过 `str` 访问器可以调用各种字符串方法。

In [59]:
# 创建示例数据
df_str = pd.DataFrame({
    'name': ['alice', 'bob', 'charlie', 'david'],
    'email': ['alice@163.com', 'bob@gmail.com', 'charlie@qq.com', 'david@hotmail.com']
})

# 将名字首字母大写
df_str['name'] = df_str['name'].str.capitalize()
print("首字母大写后的名字：")
print(df_str['name'])

首字母大写后的名字：
0      Alice
1        Bob
2    Charlie
3      David
Name: name, dtype: str

In [60]:
# 提取邮箱域名（@ 后面的部分）
df_str['email_domain'] = df_str['email'].str.extract(r'@(.+)')
print("\n提取邮箱域名：")
df_str[['email', 'email_domain']]

提取邮箱域名：

               email email_domain
0      alice@163.com      163.com
1      bob@gmail.com    gmail.com
2     charlie@qq.com       qq.com
3  david@hotmail.com  hotmail.com

---

## 总结

本教程涵盖了 Pandas DataFrame 的核心操作：

1. **创建方式**：从字典、Series、CSV 文件等多种方式创建 DataFrame
2. **属性查看**：通过 index、columns、values、dtypes、shape 等属性了解数据结构
3. **数据访问**：loc、iloc、at、iat 等方法用于精确访问数据
4. **布尔索引**：通过条件表达式筛选数据
5. **缺失值处理**：isna、dropna、fillna 处理缺失值
6. **重复值处理**：duplicated、drop_duplicates 处理重复数据
7. **统计方法**：describe、mean、sum 等计算描述性统计
8. **排序操作**：sort_index、sort_values、nlargest、nsmallest 进行排序
9. **数据变形**：melt、pivot 实现宽表与长表互转，split 分割字符串
10. **分组聚合**：groupby 结合聚合函数进行分组统计

掌握这些技能将帮助你高效地完成数据分析任务。